Add fastSAM
Cubevoid/atari-obj-pred pull request #10
Opened 2024-03-11 22:56 UTC by Cubevoid

Not sure what the right way to resize the images is, or to suppress the warnings

2024-03-12 22:51 UTC, Cubevoid commented
TODO: dataloader needs to accept new file format

2024-03-15 14:17 UTC, quajak requested changes

2024-03-15 14:17 UTC, quajak commented on src/data_collection/data_loader.py
> +        states_tensor  = states_tensor .permute(0, 4, 1, 2, 3)
```suggestion
        states_tensor = states_tensor.permute(0, 4, 1, 2, 3)
```

2024-03-15 14:17 UTC, quajak commented on src/data_collection/data_loader.py
> +        states_tensor  = states_tensor  / 255
```suggestion
        states_tensor = states_tensor / 255
```

2024-03-15 14:17 UTC, quajak commented on src/data_collection/data_loader.py
> +        object_bounding_boxes_tensor= torch.from_numpy(np.array(object_bounding_boxes_list))
```suggestion
        object_bounding_boxes_tensor = torch.from_numpy(np.array(object_bounding_boxes_list))
```

2024-03-15 14:19 UTC, quajak approved these changes

2024-03-15 14:24 UTC, BENEDIDIN approved these changes

2024-03-15 14:27 UTC, merged